In [58]:
import math
e_const=math.e
pi_const=math.pi
import statistics
import numpy as np
from fractions import Fraction
from decimal import Decimal

def add(x, y):
    last_result=x+y
    return last_result

def subtract(x, y):
    last_result= x - y
    return last_result

def multiply(x, y):
    last_result= x * y
    return last_result

def divide(x, y):
    if y == 0:
        return "Error: Cannot divide by zero"
    else:
        last_result= x / y
        return last_result

def power(x, y):
    last_result= x ** y
    return last_result

def square_root(x):
    last_result= math.sqrt(x)
    return last_result

def variable_root(x,y):
    last_result= x**(1/y)
    return last_result

def sin(x):
    last_result= math.sin(math.radians(x))
    return last_result

def cos(x):
    last_result= math.cos(math.radians(x))
    return last_result

def tan(x):
    last_result= math.tan(math.radians(x))
    return last_result

def sinh(x):
    last_result= math.sinh(math.radians(x))
    return last_result

def cosh(x):
    last_result= math.cosh(math.radians(x))
    return last_result

def tanh(x):
    last_result= math.tanh(math.radians(x))
    return last_result

def logarithm(x):
    last_result= math.log10(x)
    return last_result

def logarithm_base2(x):
    last_result= math.log2(x)
    return last_result

def ln(x):
    last_result= math.log(x)
    return last_result

def exponential(x):
    last_result= e_const**x
    return last_result

def mean(*x):
    last_result= statistics.mean(x)
    return last_result

def variance(*x):
    last_result= statistics.variance(x)
    return last_result

def standard_deviation(*x):
    last_result= statistics.stdev(x)
    return last_result

def decimal_value(x):
    last_result= Decimal(x)
    return last_result

def fraction_value(x):
    last_result= Fraction(x)
    return last_result

def factorial(x):
    last_result=1
    for i in range (1,x+1,1):
        last_result*=i
    return last_result

def permutation(x,y):
    z=x-y
    last_result= factorial(x)/factorial(z)
    return last_result

def combination(x,y):
    z=x-y
    last_result= factorial(x)/(factorial(y)*factorial(z))
    return last_result

def meters_to_feet(meters):
    last_result= meters * 3.28084
    return last_result

def feet_to_meters(feet):
    last_result= feet / 3.28084
    return last_result

def kilograms_to_pounds(kilograms):
    last_result= kilograms * 2.20462
    return last_result

def pounds_to_kilograms(pounds):
    last_result= pounds / 2.20462
    return last_result

def liters_to_gallons(liters):
    last_result= liters * 0.264172
    return last_result

def gallons_to_liters(gallons):
    last_result= gallons / 0.264172
    return last_result

def solve_linear_eqn(a, b):
    if a == 0:
        raise ValueError("Coefficient 'a' cannot be zero.")
    return -b / a

def solve_quadratic_eqn(a, b, c):
    discriminant = b**2 - 4*a*c
    if discriminant > 0:
        root1 = (-b + math.sqrt(discriminant)) / (2*a)
        root2 = (-b - math.sqrt(discriminant)) / (2*a)
        return root1, root2
    elif discriminant == 0:
        root = -b / (2*a)
        return root,
    else:
        realPart = -b / (2*a)
        imaginaryPart = math.sqrt(-discriminant) / (2*a)
        return (realPart + imaginaryPart*1j, realPart - imaginaryPart*1j)
def find_polynomial_eqn(a,b,c):
    coefficients=[a,b,c]
    roots = np.roots(coefficients)
    return roots

def matrix_addition(matrix1,matrix2):
    return np.add(matrix1, matrix2)

def matrix_subtraction(matrix1,matrix2):
    return np.subtract(matrix1, matrix2)

def matrix_multiplication(matrix1,matrix2):
    return np.dot(matrix1, matrix2)

def matrix_det(matrix):
    return np.linalg.det(matrix)

def matrix_inv(matrix):
    try:
     result=np.linalg.inv(matrix)
    except np.linalg.LinAlgError:
     result='error'
    return result

def matrix_transpose(matrix):
    return np.transpose(matrix)

def show_operations():
    print("Available operations:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Power (^)")
    print("6. Square Root (sqrt)")
    print("7. Variable Root (root)")
    print("8. Sine (sin)")
    print("9. Cosine (cos)")
    print("10. Tangent (tan)")
    print("11. Hyperbolic Sine (sinh)")
    print("12. Hyperbolic Cosine (cosh)")
    print("13. Hyperbolic Tangent (tanh)")
    print("14. Logarithm (log10)")
    print("15. Logarithm Base 2 (log2)")
    print("16. Natural Logarithm (ln)")
    print("17. Exponential (exp)")
    print("18. Mean (mean)")
    print("19. Variance (variance)")
    print("20. Standard Deviation (stdev)")
    print("21. Decimal Value (decimal)")
    print("22. Fraction Value (fraction)")
    print("23. Factorial (factorial)")
    print("24. Permutation (perm)")
    print("25. Combination (comb)")
    print("26. Meters to Feet (m2ft)")
    print("27. Feet to Meters (ft2m)")
    print("28. Kilograms to Pounds (kg2lb)")
    print("29. Pounds to Kilograms (lb2kg)")
    print("30. Liters to Gallons (L2G)")
    print("31. Gallons to Liters (G2L)")
    print("32. Solve Linear Equation (linear)")
    print("33. Solve Quadratic Equation (quadratic)")
    print("34. Find Polynomial Roots (polynomial)")
    print("35. Matrix Addition (mat_add)")
    print("36. Matrix Subtraction (mat_sub)")
    print("37. Matrix Multiplication (mat_mul)")
    print("38. Matrix Determinant (mat_det)")
    print("39. Matrix Inverse (mat_inv)")
    print("40. Matrix Transpose (mat_trans)")
    print("41. Store to Memory (M)")
    print("42. Recall Memory (MR)")
    print("43. Add to Memory (M+)")
    print("44. Subtract from Memory (M-)")
    print("45. Clear Memory (MC)")
    print("46. Exit (q)")

def calculator():
    show_operations()

    memory = 0  
    last_result=0
    while True:
        choice = input("Enter your choice: ").strip().lower()

        if choice == 'q':
            print("Goodbye!")
            break
        elif choice in ['+', '-', '*', '/', '^']:
            x = float(input("Enter first number: "))
            y = float(input("Enter second number: "))
            if choice == '+':
                print(f"Result: {add(x, y)}")
                last_result=add(x, y)
            elif choice == '-':
                print(f"Result: {subtract(x, y)}")
                last_result=subtract(x, y)
            elif choice == '*':
                print(f"Result: {multiply(x, y)}")
                last_result=multiply(x, y)
            elif choice == '/':
                print(f"Result: {divide(x, y)}")
                last_result=divide(x, y)
            elif choice == '^':
                print(f"Result: {power(x, y)}")
                last_result=power(x, y)
        elif choice == 'sqrt':
            x = float(input("Enter number: "))
            print(f"Result: {square_root(x)}")
            last_result=square_root(x)
        elif choice == 'root':
            x = float(input("Enter base: "))
            y = float(input("Enter root: "))
            print(f"Result: {variable_root(x, y)}")
            last_result=variable_root(x, y)
        elif choice == 'sin':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {sin(x)}")
            last_result=sin(x)
        elif choice == 'cos':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {cos(x)}")
            last_result=cos(x)
        elif choice == 'tan':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {tan(x)}")
            last_result=tan(x)
        elif choice == 'sinh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {sinh(x)}")
            last_result=sinh(x)
        elif choice == 'cosh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {cosh(x)}")
            last_result=cosh(x)
        elif choice == 'tanh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {tanh(x)}")
            last_result=tanh(x)
        elif choice == 'log10':
            x = float(input("Enter number: "))
            print(f"Result: {logarithm(x)}")
            last_result=logarithm(x)
        elif choice == 'log2':
            x = float(input("Enter number: "))
            print(f"Result: {logarithm_base2(x)}")
            last_result=logarithm_base2(x)
        elif choice == 'ln':
            x = float(input("Enter number: "))
            print(f"Result: {ln(x)}")
            last_result=ln(x)
        elif choice == 'exp':
            x = float(input("Enter exponent: "))
            print(f"Result: {exponential(x)}")
            last_result=exponential(x)
        elif choice == 'mean':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {mean(*nums)}")
            last_result=mean(*nums)
        elif choice == 'variance':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {variance(*nums)}")
            last_result=variance(*nums)
        elif choice == 'stdev':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {standard_deviation(*nums)}")
            last_result=standard_deviation(*nums)
        elif choice == 'decimal':
            x = input("Enter number: ")
            print(f"Result: {decimal_value(x)}")
            last_result=decimal_value(x)
        elif choice == 'fraction':
            x = input("Enter number: ")
            print(f"Result: {fraction_value(x)}")
            last_result=fraction_value(x)
        elif choice == 'factorial':
            x = int(input("Enter number: "))
            print(f"Result: {factorial(x)}")
            last_result=factorial(x)
        elif choice == 'perm':
            x = int(input("Enter n: "))
            y = int(input("Enter r: "))
            print(f"Result: {permutation(x, y)}")
            last_result=permutation(x, y)
        elif choice == 'comb':
            x = int(input("Enter n: "))
            y = int(input("Enter r: "))
            print(f"Result: {combination(x, y)}")
            last_result=combination(x, y)
        elif choice == 'm2ft':
            meters = float(input("Enter meters: "))
            print(f"Result: {meters_to_feet(meters)}")
            last_result=meters_to_feet(meters)
        elif choice == 'ft2m':
            feet = float(input("Enter feet: "))
            print(f"Result: {feet_to_meters(feet)}")
            last_result=feet_to_meters(feet)
        elif choice == 'kg2lb':
            kilograms = float(input("Enter kilograms: "))
            print(f"Result: {kilograms_to_pounds(kilograms)}")
            last_result=kilograms_to_pounds(kilograms)
        elif choice == 'lb2kg':
            pounds = float(input("Enter pounds: "))
            print(f"Result: {pounds_to_kilograms(pounds)}")
            last_result=pounds_to_kilograms(pounds)
        elif choice == 'l2g':
            liters = float(input("Enter liters: "))
            print(f"Result: {liters_to_gallons(liters)}")
            last_result=liters_to_gallons(liters)
        elif choice == 'g2l':
            gallons = float(input("Enter gallons: "))
            print(f"Result: {gallons_to_liters(gallons)}")
            last_result=gallons_to_liters(gallons)
        elif choice == 'linear':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            print(f"Result: {solve_linear_eqn(a, b)}")
        elif choice == 'quadratic':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            c = float(input("Enter coefficient c: "))
            print(f"Result: {solve_quadratic_eqn(a, b, c)}")
        elif choice == 'polynomial':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            c = float(input("Enter coefficient c: "))
            print(f"Roots: {find_polynomial_eqn(a, b, c)}")
        elif choice == 'mat_add':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_addition(matrix1, matrix2)}")
        elif choice == 'mat_sub':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_subtraction(matrix1, matrix2)}")
        elif choice == 'mat_mul':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_multiplication(matrix1, matrix2)}")
        elif choice == 'mat_det':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_det(matrix)}")
        elif choice == 'mat_inv':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_inv(matrix)}")
        elif choice == 'mat_trans':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_transpose(matrix)}")
        elif choice == 'store to memory':
            memory = last_result
            print(f"Stored {memory} in memory.")
        elif choice == 'recall memory':
            print(f"Recalled memory: {memory}")
        elif choice == 'add to memory':
            memory += last_result
            print(f"Added {last_result} to memory. New memory: {memory}")
        elif choice == 'subtract from memory':
            memory -= last_result
            print(f"Subtracted {last_result} from memory. New memory: {memory}")
        elif choice == 'clear memory':
            memory = 0
            print("Memory cleared.")
        else:
            print("Invalid choice. Please select a valid operation or 'q' to quit.")

In [254]:
add(2,3)

5

In [255]:
subtract(0, 2)

-2

In [256]:
multiply(3, 5)

15

In [257]:
divide(2, 2)

1.0

In [258]:
divide(2, 0)

'Error: Cannot divide by zero'

In [259]:
power(3, 2)

9

In [260]:
square_root(16)

4.0

In [261]:
variable_root(27,3)

3.0

In [262]:
sin(30)

0.49999999999999994

In [263]:
cos(60)

0.5000000000000001

In [264]:
tan(45)

0.9999999999999999

In [265]:
sinh(30)

0.5478534738880397

In [266]:
cosh(60)

1.600286857702386

In [267]:
tanh(45)

0.6557942026326724

In [268]:
logarithm(10)

1.0

In [269]:
logarithm_base2(6)

2.584962500721156

In [270]:
ln(e_const)

1.0

In [271]:
exponential(0)

1.0

In [272]:
mean(1,2,3,4)

2.5

In [273]:
variance(1,2,3,4)

1.6666666666666667

In [274]:
standard_deviation(1,2,3,4)

1.2909944487358056

In [275]:
fraction_value(0.25)

Fraction(1, 4)

In [276]:
decimal_value(1/2)

Decimal('0.5')

In [277]:
factorial(5)

120

In [278]:
permutation(5,2)

20.0

In [279]:
combination(5,2)

10.0

In [280]:
meters_to_feet(1)

3.28084

In [281]:
feet_to_meters(3.28084)

1.0

In [282]:
kilograms_to_pounds(1)

2.20462

In [283]:
pounds_to_kilograms(2.20462)

1.0

In [284]:
liters_to_gallons(1)

0.264172

In [285]:
gallons_to_liters(0.264172)

1.0

In [286]:
solve_linear_eqn(2,-4)

2.0

In [287]:
solve_quadratic_eqn(1, -3, 2)

(2.0, 1.0)

In [288]:
solve_quadratic_eqn(1, 2, 5)

((-1+2j), (-1-2j))

In [289]:
find_polynomial_eqn(1,-3,2)

array([2., 1.])

In [290]:
find_polynomial_eqn(1,-3,3)

array([1.5+0.8660254j, 1.5-0.8660254j])

In [291]:
matrix1=[[2,2],[3,3]]
matrix2=[[1,1],[1,1]]
matrix_addition(matrix1,matrix2)

array([[3, 3],
       [4, 4]])

In [292]:
matrix_subtraction(matrix1,matrix2)

array([[1, 1],
       [2, 2]])

In [293]:
matrix3=[1,1,1]
matrix4=[[2],[2],[2]]
matrix_multiplication(matrix3,matrix4)

array([6])

In [294]:
matrix_det(matrix1)

-3.330669073875464e-16

In [295]:
matrix_inv(matrix1)

array([[-9.00719925e+15,  6.00479950e+15],
       [ 9.00719925e+15, -6.00479950e+15]])

In [296]:
matrix_transpose(matrix1)

array([[2, 3],
       [2, 3]])

In [16]:
add(2,4)

6

In [60]:
calculator()

Available operations:
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Power (^)
6. Square Root (sqrt)
7. Variable Root (root)
8. Sine (sin)
9. Cosine (cos)
10. Tangent (tan)
11. Hyperbolic Sine (sinh)
12. Hyperbolic Cosine (cosh)
13. Hyperbolic Tangent (tanh)
14. Logarithm (log10)
15. Logarithm Base 2 (log2)
16. Natural Logarithm (ln)
17. Exponential (exp)
18. Mean (mean)
19. Variance (variance)
20. Standard Deviation (stdev)
21. Decimal Value (decimal)
22. Fraction Value (fraction)
23. Factorial (factorial)
24. Permutation (perm)
25. Combination (comb)
26. Meters to Feet (m2ft)
27. Feet to Meters (ft2m)
28. Kilograms to Pounds (kg2lb)
29. Pounds to Kilograms (lb2kg)
30. Liters to Gallons (L2G)
31. Gallons to Liters (G2L)
32. Solve Linear Equation (linear)
33. Solve Quadratic Equation (quadratic)
34. Find Polynomial Roots (polynomial)
35. Matrix Addition (mat_add)
36. Matrix Subtraction (mat_sub)
37. Matrix Multiplication (mat_mul)
38. Matrix Determinant (ma

Enter your choice:  +
Enter first number:  4
Enter second number:  7


Result: 11.0


Enter your choice:  store to memory


Stored 11.0 in memory.


Enter your choice:  recall memory


Recalled memory: 11.0


Enter your choice:  add to memory


Added 11.0 to memory. New memory: 22.0


Enter your choice:  subtract from memory


Subtracted 11.0 from memory. New memory: 11.0


Enter your choice:  clear memory


Memory cleared.


Enter your choice:  q


Goodbye!
